version: "3.7"

services:
  mysql:
    image: mysql:8.0.32
    volumes:
      - capstone-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: capstone


volumes:
  capstone-mysql-data:
